import type { LiveIndexPool } from "@/types/pool";

export const DEMO_POOLS: LiveIndexPool[] = [
  {
    id: "arsenal",
    teamName: "ARSENAL",
    symbol: "$pAFC",
    status: "open",
    indexValue: 1.24,
    change: 3.4,
    holders: 847,
    poolFill: "71%",
    poolSize: "$142.5K",
    poolCap: "$200K",
    tags: ["USDC / CHZ", "Gains Eligible", "Listing Soon"],
  },
  {
    id: "mancity",
    teamName: "MAN CITY",
    symbol: "$pCITY",
    status: "closing soon",
    indexValue: 2.18,
    change: 1.8,
    holders: 1203,
    poolFill: "94%",
    poolSize: "$187.2K",
    poolCap: "$200K",
    tags: ["USDC / CHZ", "Gains Eligible", "Listing Soon"],
  },
  {
    id: "okc",
    teamName: "OKC THUNDER",
    symbol: "$pOKC",
    status: "open",
    indexValue: 0.87,
    change: -0.5,
    holders: 634,
    poolFill: "60%",
    poolSize: "$89.4K",
    poolCap: "$150K",
    tags: ["USDC / CHZ", "Gains Eligible", "Listing Soon"],
  },
  {
    id: "spurs",
    teamName: "SA SPURS",
    symbol: "$pSAS",
    status: "closed",
    indexValue: 1.45,
    change: 0.0,
    holders: 892,
    poolFill: "100%",
    poolSize: "$150K",
    poolCap: "$150K",
    tags: ["USDC / CHZ", "Gains Eligible", "Listing Soon"],
    disabled: true,
  },
];
